# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shenjunwei/fruits-plans/mango/ParseMp3tag

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shenjunwei/fruits-plans/mango/ParseMp3tag

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shenjunwei/fruits-plans/mango/ParseMp3tag/CMakeFiles /Users/shenjunwei/fruits-plans/mango/ParseMp3tag/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shenjunwei/fruits-plans/mango/ParseMp3tag/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mp3parser

# Build rule for target.
mp3parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mp3parser
.PHONY : mp3parser

# fast build rule for target.
mp3parser/fast:
	$(MAKE) -f CMakeFiles/mp3parser.dir/build.make CMakeFiles/mp3parser.dir/build
.PHONY : mp3parser/fast

mp3edit.o: mp3edit.c.o

.PHONY : mp3edit.o

# target to build an object file
mp3edit.c.o:
	$(MAKE) -f CMakeFiles/mp3parser.dir/build.make CMakeFiles/mp3parser.dir/mp3edit.c.o
.PHONY : mp3edit.c.o

mp3edit.i: mp3edit.c.i

.PHONY : mp3edit.i

# target to preprocess a source file
mp3edit.c.i:
	$(MAKE) -f CMakeFiles/mp3parser.dir/build.make CMakeFiles/mp3parser.dir/mp3edit.c.i
.PHONY : mp3edit.c.i

mp3edit.s: mp3edit.c.s

.PHONY : mp3edit.s

# target to generate assembly for a file
mp3edit.c.s:
	$(MAKE) -f CMakeFiles/mp3parser.dir/build.make CMakeFiles/mp3parser.dir/mp3edit.c.s
.PHONY : mp3edit.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mp3parser"
	@echo "... mp3edit.o"
	@echo "... mp3edit.i"
	@echo "... mp3edit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

